version: "3.0"
services:
  frontend:
    restart: always
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - DAEMON_HOST=daemon
      - MONGODB_HOST=mongodb
  daemon:
    restart: always
    build: https://github.com/CM2Walki/scalexctl.git
    ports:
      - "20000:20000"
    depends_on:
      - mongodb
      - frontend
    environment:
      - MONGODB_HOST=mongodb
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./db:/data/db
