version: "3.0"
services:
  frontend:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: always
  daemon:
    build: https://github.com/CM2Walki/ScaleX-tune
    ports:
      - "20000:20000"
    depends_on:
      - mongodb
    restart: always
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./db:/data/db
