version: "3.0"
services:
  server-service:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      - mongodbinst
    links:
      - mongodbinst
    restart: always
  mongodbinst:
    image: mongo:latest
    ports:
      - "27017:27017"
